brand_names = {'10 crosby derek lam': 'derek lam',
               '14510 pally': 'rachel pally',
               '14510 zoe': 'zoë',
               '2brych': '2b.rych',
               'rare atelier swarovski crystal bracelet custom': 'atelier swarovski',
               'abbys by abby': 'abyss by abby',
               'abyss': 'abyss by abby',
               'acne': 'acne studios',
               'acne baroque': 'acne studios',
               'alexia admor nyc': 'alexia admor',
               'alexia. admor': 'alexia admor',
               'alice and trixie': 'alice & trixie',
               'anthropology': 'anthropologie',
               'alice&olivia': 'alice + olivia',
               'alice and olivia': 'alice + olivia',
               'alice+olivia': 'alice + olivia',
               'a.l.c': 'a.l.c.',
               'a.s.h': 'ash',
               'alice by temperley': 'temperley london',
               'alice by temperley london': 'temperley london',
               'ark & co': 'ark & co.',
               'aidan': 'aidan mattox',
               'aidan by aidan mattox': 'aidan mattox',
               'antionio berardi': 'antonio berardi',
               'altazurra': 'altuzarra',
               'alyce designs': 'alyce paris',
               'aquazurra': 'aquazzura',
               'aquilano irimondi': 'aquilano rimondi',
               'armani': 'giorgio armani',
               'armani collezioni': 'giorgio armani',
               'armani exchange': 'giorgio armani',
               'emporio armani': 'giorgio armani',
               'auguste': 'auguste the label',
               'bailey': 'bailey44',
               'bailey 44': 'bailey44',
               'balmain x h&m': 'balmain',
               'bariano australia': 'bariano',
               'basix ii': 'basix',
               'be bop': 'bebop',
               'beaded panel one-shoulder jersey gown': 'laundry by shelli segal',
               'beguile by byron lars': 'byron lars',
               'bibu mohapatra': 'bibhu mohapatra',
               'boutique from top shop': 'topshop',
               'burberry london': 'burberry',
               'by malene birger': 'malene birger',
               'c&t costello tagliapietra': 'costello tagliapietra',
               'carribean queen': 'caribbean queen',
               'carmella': 'caramella',
               'catherine catherine malandrino': 'catherine malandrino',
               'bec & bridge': 'bec + bridge',
               'bec and bridge': 'bec + bridge',
               'badgley mischika': 'badgley mischka',
               'badgley mischka collection': 'badgley mischka',
               'bagley mischka': 'badgley mischka',
               'mark & james': 'badgley mischka',
               'mark + james by badgley mischka': 'badgley mischka',
               'mark and james by badgley mischka': 'badgley mischka',
               'belle badgley mischka': 'badgley mischka',
               'betsy johnson': 'betsey johnson',
               'betsy and adam': 'betsy & adam',
               'bcbg max azria': 'bcbg',
               'bcbg maxazria': 'bcbg',
               'bcbg runway': 'bcbg',
               'bcbgeneration': 'bcbg',
               'bcbgma': 'bcbg',
               'bcbgmaxazria': 'bcbg',
               'bcbgmaxazria runway': 'bcbg',
               'bcbgmaxzaria': 'bcbg',
               'barney\'s': 'barneys new york',
               'barney\'s co-op': 'barneys new york',
               'barney\'s new york': 'barneys new york',
               'b brian atwood': 'brian atwood',
               'calvin klien': 'calvin klein',
               'cind a sept': 'cinq à sept',
               'cinq a sept': 'cinq à sept',
               'carmen marc valco': 'carmen marc valvo',
               'carmen marc valvo collection': 'carmen marc valvo',
               'carmen marc valvo infusion': 'carmen marc valvo',
               'camilla franks': 'camilla',
               'redux by charles chang-lima': 'charles chang-lima',
               'dior': 'christian dior',
               'diane von furstenberg': 'dvf',
               'divf': 'dvf',
               'doma': 'damir doma',
               'donna karan collection': 'donna karan',
               'dsquared': 'dsquared2',
               'eliza': 'eliza j',
               'eliza j cap': 'eliza j',
               'eliza j new york': 'eliza j',
               'eliza. j': 'eliza j',
               'elizabeth and james. i have a sample of this dress in a purple/wine color': 'elizabeth and james',
               'elizabetta franchi': 'elisabetta franchi',
               'ellen tracey': 'ellen tracy',
               'ellie tahari': 'elie tahari',
               'enrose': 'la vie enrose',
               'enza': 'enza costa',
               'equipment femme': 'equipment',
               'erin': 'erin fetherston',
               'erin erin fetherston': 'erin fetherston',
               'esley': 'esley collection',
               'essentiel': 'essentiel antwerp',
               'eva mendes apparel': 'eva mendes',
               'faithful the brand': 'faithfull the brand',
               'fame & partners': 'fame and partners',
               'farina': 'fashion by farina',
               'ff': 'f&f',
               'finder\'s keepers': 'finders keepers',
               'foley & corina': 'foley & corinna',
               'for love and lemons': 'for love & lemons',
               'for restless sleepers': 'f.r.s. for restless sleepers',
               'ford': 'tom ford',
               'forever. 21': 'forever 21',
               'forever21': 'forever 21',
               'frame denim': 'frame',
               'laundry': 'laundry by shelli segal',
               'laundry by shelli': 'laundry by shelli segal',
               'laundry by shelli seagal': 'laundry by shelli segal',
               'lover + friends': 'lovers + friends',
               'louis vitton': 'louis vuitton',
               'louis vuitton damier pouch': 'louis vuitton',
               'louboutin': 'christian louboutin',
               'louboutin decollete': 'christian louboutin',
               'louboutin pigalle multiglitter': 'christian louboutin',
               'christian louboutin boots': 'christian louboutin',
               'christian louboutin size 7': 'christian louboutin',
               'chelsea 28': 'chelsea28',
               'carolina herrara': 'carolina herrera',
               'current/elliot': 'current/elliott',
               'chloe': 'chloé',
               'cache': 'caché',
               'see by chloe': 'chloé',
               'calypso': 'calypso st. barth',
               'love shack fancy': 'loveshackfancy',
               'olivia palermo + chelsea28': 'chelsea28',
               'celine': 'céline',
               'ceremony by joanna august': 'joanna august',
               'chado': 'chado ralph rucci',
               'christopher kane for topshop': 'topshop',
               'cj by cookie johnson': 'cookie johnson',
               'clare vivier': 'clare v.',
               'classiques entier®': 'classiques entier',
               'cluce': 'c. luce',
               'cop copine': 'cop. copine',
               'coreylynn calter': 'corey lynn calter',
               'crop david peck': 'david peck',
               'd squared': 'dsquared2',
               'david dielden': 'david fielden',
               'david lerner': 'david lerner new york',
               'gavinchy paris': 'givenchy',
               'giamba': 'giambattista valli',
               'giannvito rossi': 'gianvito rossi',
               'ginger': 'ginger g',
               'glamour by terani couture': 'terani couture',
               'guess by marciano': 'guess',
               'gypsy 05': 'gypsy05',
               'hailey by adrianna papell': 'hailey logan',
               'hailey logan by adrianna papell': 'hailey logan',
               'haily logan': 'hailey logan',
               'halebob': 'hale bob',
               'halston': 'halston heritage',
               'hautie hippie': 'haute hippie',
               'hayley paige occasions': 'hayley paige',
               'heart & noble': 'heart and noble',
               'helmut by helmut lang': 'helmut lang',
               'hermes': 'hermès',
               'hervé l. leroux': 'herve leger',
               'hunter dell': 'hunter bell',
               'hunter dixon by hunter bell': 'hunter bell',
               'indian clothe saari': 'indian cloth saari',
               'intermix exclusive': 'intermix',
               'one by honey punch': 'honey punch',
               'one by naven': 'naven',
               'opening cermony': 'opening ceremony',
               'ostwald helgasson x aldo': 'ostwald helgason',
               'isabel marant etoile': 'isabel marant',
               'issa london': 'issa',
               'issa phylis': 'issa',
               'issue ny': 'issue new york',
               'j mclaughlin': 'j.mclaughlin',
               'j. mclaughlin': 'j.mclaughlin',
               'j mendel': 'j. mendel',
               'jcrew': 'j.crew',
               'j crew': 'j.crew',
               'jetset diaries': 'the jetset diaries',
               'jet set diaries': 'the jetset diaries',
               'jérôme dreyfuss': 'jerome dreyfuss',
               'jil sander navy': 'jil sander',
               'jill sander': 'jil sander',
               'jill sanders': 'jil sander',
               'jill jill stuart': 'jill stuart',
               'jimmy choo for h & m': 'jimmy choo',
               'joa': 'j.o.a.',
               'joan david': 'joan & david',
               'jodi': 'jodi arnold',
               'jonathon saunders': 'jonathan saunders',
               'johnathan simkhai': 'jonathan simkhai',
               'jonathan simkahi': 'jonathan simkhai',
               'juice couture': 'juicy couture',
               'kamalikulture': 'norma kamali',
               'kate moss for topshop': 'topshop',
               'kate spade': 'kate spade new york',
               'kate spade saturdays': 'kate spade new york',
               'kate spade.': 'kate spade new york',
               'katherine malandrino': 'catherine malandrino',
               'katya lee designs': 'katya lee',
               'keepsake': 'keepsake the label',
               'kelima': 'kelima k',
               'kerrigan': 'daryl kerrigan',
               'lamb': 'l.a.m.b.',
               'l.k. bennett': 'l.k. bennett',
               'la petite robe by chiara boni': 'chiara boni',
               'la petite robe di chiara boni': 'chiara boni',
               'lafayette 148': 'lafayette 148 new york',
               'lattori collection': 'lattori',
               'lauren by ralph lauren': 'ralph lauren',
               'lauren ralph lauren': 'ralph lauren',
               'lavender label vera wang': 'vera wang',
               'layla azhar': 'laila azhar',
               'leifsdottir': 'anthropologie', # (acquired)
               'lela rose bridesmaid': 'lela rose',
               'leon max limited edition': 'leon max',
               'liebeskind berlin': 'liebeskind',
               'light in the box': 'lightinthebox',
               'lila eugine': 'lila eugenie',
               'lilly for target': 'lilly pulitzer',
               'lilly pulitzer for target': 'lilly pulitzer',
               'lilly pulitzer, sophie dress': 'lilly pulitzer',
               'lilly pulitzer®': 'lilly pulitzer',
               'lily pulitzer': 'lilly pulitzer',
               'lipsy': 'lipsy london',
               'lipsy vip': 'lipsy london',
               'lk lakore': 'la kore',
               'london times': 'maggy london',
               'love moschino': 'moschino',
               'lucy & co': 'lucy & co.',
               'lulu\'s': 'lulus',
               'lv': 'louis vuitton',
               'm missoni': 'missoni',
               'macys': 'macy\'s',
               'madwell chambray jumpsuit': 'madwell',
               'maids rory beca': 'rory beca',
               'maison martin margiela': 'maison margiela',
               'marc by marc jacobs': 'marc jacobs',
               'marciano': 'guess',
               'marciano by guess': 'guess',
               'maria lucia hohan': 'mhl maria lucia hohan',
               'marques almeida': 'marques\'almeida',
               'martin margiela': 'maison margiela',
               'mason': 'michelle mason',
               'mason by michelle mason': 'michelle mason',
               'max & cleo': 'max and cleo',
               'max mara': 'maxmara',
               'max mara (sportmax)': 'maxmara',
               'max mara (weekend)': 'maxmara',
               'mcq alexander mcqueen': 'alexander mcqueen',
               'meteo by yves salomon': 'yves salomon',
               'michael by michael kors': 'michael kors',
               'michael michael kors': 'michael kors',
               'milly new york': 'milly',
               'misguided': 'missguided',
               'misha': 'misha collection',
               'miss lily': 'miss lilly',
               'modefa by fely tchaco': 'fely tchaco',
               'moschino couture': 'moschino',
               'muses by shop': 'muse',
               'myne ashley ann': 'myne',
               'n/ nicholas': 'nicholas',
               'nanette lapore': 'nanette lepore',
               'narisco rodriguez': 'narciso rodriguez',
               'nasty girl': 'nasty gal',
               'nastygal': 'nasty gal',
               'nicholas': 'nicholas kirkwood',
               'nicolas kirkwood': 'nicholas kirkwood',
               'nicole miller collection': 'nicole miller',
               'nicole miller new york': 'nicole miller',
               'nightcap': 'nightcap clothing',
               'nightcap x carisa rene': 'nightcap clothing',
               'manolo blahnik sandals': 'manolo blahnik',
               'manolo blahnik slingback sandals': 'manolo blahnik',
               'marchesa notte': 'marchesa',
               'marchesa voyage': 'marchesa',
               'marchessa "notte"': 'marchesa',
               'pearl georgina chapman of marchesa': 'marchesa',
               'suzi chin': 'maggy boutique',
               'suzi chin by maggy boutique': 'maggy boutique',
               'suzi chin for maggy boutique': 'maggy boutique',
               'ml monique lhuillier': 'monique lhuillier',
               'monique': 'monique lhuillier',
               'monique l\'huillier': 'monique lhuillier',
               'monique l\'hullier': 'monique lhuillier',
               'monique lhuillier': 'monique lhuillier',
               'monique lhuillier bridesmaids': 'monique lhuillier',
               'monqiue l\'hullier': 'monique lhuillier',
               'peace by lotta stensson': 'lotta stensson',
               'parker': 'parker ny',
               'parker black': 'parker ny',
               'paul&joe': 'paul & joe',
               '3.1  phillip lim': '3.1 phillip lim',
               'philip lim': '3.1 phillip lim',
               'phillip lim': '3.1 phillip lim',
               'piazza. sempione': 'piazza sempione',
               'ports': 'ports 1961',
               'rachel rachel roy': 'rachel roy',
               'ralph lauren black label': 'ralph lauren',
               'ralph lauren evening size 4': 'ralph lauren',
               'ray bans': 'ray-ban',
               'slate & willow': 'rent the runway',
               'slate and willow': 'rent the runway',
               'robert rodriguez collection': 'robert rodriguez',
               'roberto caballi': 'roberto cavalli',
               'sachin & babi noir': 'sachin & babi',
               'saks 5th avenue': 'saks fifth avenue',
               'asap saks': 'saks fifth avenue',
               'self portait': 'self-portrait',
               'self portrait': 'self-portrait',
               'selt portrait': 'self-portrait',
               'shakunachi': 'shakuhachi',
               'sheri bodel': 'sheri bodell',
               'sherry hill': 'sherri hill',
               'shoshanna midnight': 'shoshanna',
               'sonia by sonia rykiel': 'sonia rykiel',
               'sophia koko': 'sophia kokosalaki',
               'spell': 'spell & the gypsy collective',
               'st. john collection': 'st. john',
               'stella and dot': 'stella & dot',
               'stop staring': 'stop staring!',
               'stylelend': 'style lend',
               'sara': 'sara boni',
               'shop style': 'shopstyle',
               'tanya taylor renwick': 'tanya taylor',
               'tba': 'tba to be adored',
               'ted baker london': 'ted baker',
               'terani': 'terani couture',
               'terrani': 'terani couture',
               'tnfc': 'tfnc',
               'tfnco': 'tfnc',
               'thakoon addition': 'thakoon',
               'theory andora': 'theory',
               'theory zizinna': 'theory',
               'theyskens theory': 'theory',
               'theyskens\' theory': 'theory',
               'times arrow': 'time\'s arrow',
               'to be adored': 'tba to be adored',
               'vince': 'vince.',
               'vivenne westwood (red label)': 'vivienne westwood',
               'w118 by walter baker': 'walter baker',
               'yoga army': 'yoga',
               't+j designs': 't + j designs',
               't by alexander wang': 'alexander wang',
               'temperley': 'temperley london',
               'tirana jewlery': 'tirana jewelry',
               'top shop': 'topshop',
               'tory richard': 'tori richard',
               'trina turk for banana republic': 'trina turk',
               'trina turka': 'trina turk',
               'trina. turk': 'trina turk',
               'two birds': 'twobirds bridesmaid',
               'twobirds': 'twobirds bridesmaid',
               'red by valentino': 'valentino',
               'red valentino': 'valentino',
               'valentino garavani': 'valentino',
               'valentino red': 'valentino',
               'vera wang lavender label': 'vera wang',
               'versus versace': 'versace',
               'victor & rolf': 'viktor & rolf',
               'victoria victoria beckham': 'victoria beckham',
               'white house|black market': 'white house black market',
               'white-vera wang': 'vera wang',
               'worth': 'worth new york',
               'worth nyc': 'worth new york',
               'z by zach pozen': 'zac posen',
               'z spoke by zac posen': 'zac posen',
               'truly zac posen': 'zac posen',
               'yigal azrouel': 'yigal azrouël',
               'cut 25 by yigal azrouël': 'yigal azrouël',
               'cut25 by yigal azrouël': 'yigal azrouël',
               'young, fabulous & broke': 'young fabulous & broke',
               'zimmerman': 'zimmermann',
               'zigi black label': 'zigi ny'
         }
